# Form implementation generated from reading ui file './ScanGen.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.images_frm = QtWidgets.QFrame(parent=self.centralwidget)
        self.images_frm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.images_frm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.images_frm.setObjectName("images_frm")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.images_frm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scanner_video_lbl = QtWidgets.QLabel(parent=self.images_frm)
        self.scanner_video_lbl.setText("")
        self.scanner_video_lbl.setObjectName("scanner_video_lbl")
        self.horizontalLayout.addWidget(self.scanner_video_lbl)
        self.right_frame = QtWidgets.QFrame(parent=self.images_frm)
        self.right_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.right_frame.setObjectName("right_frame")
        self.right_frame_lyt = QtWidgets.QVBoxLayout(self.right_frame)
        self.right_frame_lyt.setObjectName("right_frame_lyt")
        self.qr_code_lbl = QtWidgets.QLabel(parent=self.right_frame)
        self.qr_code_lbl.setText("")
        self.qr_code_lbl.setObjectName("qr_code_lbl")
        self.right_frame_lyt.addWidget(self.qr_code_lbl)
        self.label = QtWidgets.QLabel(parent=self.right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.right_frame_lyt.addWidget(self.label)
        self.horizontalLayout.addWidget(self.right_frame)
        self.verticalLayout.addWidget(self.images_frm)
        self.text_txbx = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.text_txbx.setMaximumSize(QtCore.QSize(16777215, 200))
        self.text_txbx.setObjectName("text_txbx")
        self.verticalLayout.addWidget(self.text_txbx)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Available Cameras:"))
